services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=qflight'
      - 'MYSQL_PASSWORD=Pass12'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=qflight_service'
    ports:
      - '3307:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
